# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6beb80c9c1a2712d1a01a450eace75493eed924409adf7ca56fe352aed4b31344bdb189d651f0ee2ddb77a86b75b2644f14d6b107bd55ca96f192c9eeb25192

test:
  secret_key_base: 6ed0a6978685b5cf91bf37831e339afb4ab7649785ecab34cbe39c18aa62af2226013de49570b7cf1cc3c96d6ec5a740d1f308f199119f9e91caa50c3e8a0c31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
